### ISSUE TITLE
Message window not properly themed.

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#1]
The parchment texture is not properly removed or changed when customising themes. This makes dark themes which have a Dialog/Sheet colour dark enough to make the Base (Shaded) text white illegible when typing messages in the chat window.

![image](https://user-images.githubusercontent.com/35461692/134426033-9e4ba14d-0e7f-4da3-86ad-c96cbea6f21f.png)
![image](https://user-images.githubusercontent.com/35461692/134426058-09c3f504-b979-466b-9de7-9389aa6efb0b.png)

**Comment by mouse0270** [comment]
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json
