### ISSUE TITLE
Customising a theme doesn't automatically set the preset to "Custom"

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#11]
When altering colours in a preset the active preset is not set to custom.

This does not affect functionality however it makes resetting the preset to it's default settings more difficult, harming the overall user experience.

For example a user starts from the Cobalt Theme, changes a few of the colours or settings, saves these settings and refreshes, but realises that they ultimately do not like the changes they have made. The only way to reset to the basic Cobalt Theme is to select a different theme and then select the Cobalt Theme again.

This could be resolved by either forcing the preset to "Custom" whenever edits are made to a predefined theme or by adding a button to reset the theme to default settings.

![image](https://user-images.githubusercontent.com/35461692/134657600-39009cd8-bf44-40f6-b5ee-e33b0fa2242f.png)

**Comment by mouse0270** [comment]
I actually thought it did this, whoops. This needs to be fixed

**Comment by mouse0270** [comment]
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json
