### ISSUE TITLE
Tidy UI - Game Settings collapsible menu buttons are not styled

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#12]
Tidy UI - Game Settings adds buttons to the Module Settings menu which allow for the individual settings for specific modules to be expanded and collapsed. These elements are not styled, even when "Enable Tidy UI - Game Settings" is enabled. As the icons default to black this can make them hard to see against darker backgrounds (such as the preset "Cobalt Theme")

![image](https://user-images.githubusercontent.com/35461692/134662727-b5615b76-3b14-45bd-bfdc-b54bbfe7ffd7.png)
![image](https://user-images.githubusercontent.com/35461692/134662738-0657e632-5358-457a-9d0d-a4353f3c4b17.png)

**Comment by mouse0270** [comment]
Good Catch!

**Comment by mouse0270** [comment]
I am closing this, as I am not sure if this is still an issue on v10. If it is, please let me know and I'll re-open this issue
