### ISSUE TITLE
Text Editor not correctly themed

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#14]
The text editor is not correctly themed making it difficult to type when using a dark theme such as the included Cobalt theme on a themed window.

### In the following two cases this can be seen on the _default sheet_ while enabling DnD 5e Settings

Test item with sample text (themed correctly):
![image](https://user-images.githubusercontent.com/35461692/136670437-e5302fb6-5633-4214-b944-343ee8c210e5.png)

Test item with sample text being edited:
![image](https://user-images.githubusercontent.com/35461692/136670441-c0da4a18-7b4c-46fc-bc3a-aa3375756ddf.png)

### The issue is also present on the Tidy5e Sheet, even when it is styled.

Test item with sampled text being edited using the Tidy5e Item Sheet:
![image](https://user-images.githubusercontent.com/35461692/136670714-f33d609b-f8c2-46ba-a334-df0f607cdf80.png)

And on handouts when Foundry Stylesheet is enabled.

A handout with sample text being edited:
![image](https://user-images.githubusercontent.com/35461692/136670752-37ef3396-7542-499e-beef-f00c7440438e.png)

**Comment by mouse0270** [comment]
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json
