### ISSUE TITLE
Not Listed

### ISSUE THREAD

**Issue by ducky00** [mouse0270/lib-themer#17]
I can't find the module to install it in foundry's module browser

**Comment by mouse0270** [comment]
Which version of Foundry are you on?
![image](https://user-images.githubusercontent.com/564874/191137860-d0d2b9de-abfb-42a5-8c09-96c755962b5a.png)

**Comment by ducky00** [comment]
Oh it's just v10 right? I thought for some reason even thought it would be just v10 it would still appear in the browser. Apologize for disturbing, dude

**Comment by mouse0270** [comment]
No worries. Stuff Happens, give it a shot once you upgrade to v10
