### ISSUE TITLE
Typo in Info Colour Hint Text

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#2]
There is a typo in the hint text for Info Colour

![image](https://user-images.githubusercontent.com/35461692/134426281-a963d316-ac3a-4bd8-8969-9d0b16d1962e.png)

Text is currently: "This color will be used to style success related elements"
It should be: "This color will be used to style info related elements"

**Comment by mouse0270** [comment]
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json
