### ISSUE TITLE
Feature Request: Show player names in TidyHUD playerlist when expanded

### ISSUE THREAD

**Issue by esheyw** [mouse0270/lib-themer#20]
Current behaviour: https://gfycat.com/nicedelayedimago

Requested behaviour: Minimal UI on v9 had this as a two variable system, with one path that was less than optimal: https://gfycat.com/WindingWeightyAlbertosaurus
 it has four states:
1. both collapsed
2. player names shown but inactive players collapsed
3. player names collapsed but inactive players shown
4. both shown

with the arrow toggle being for `show/collapse inactive players`, and a separate toggle for clicking anywhere inside the group of pips for `show/hide player names`. As shown in the gif, trying to go from `player names shown, inactives collapsed` to `player names shown, inactives shown` incorrectly goes to `player names collapsed, inactives shown`, but I'd call that a bug IMO.

Personally I would be fine with only two states, both collapsed or both shown, but the four state model could potentially accommodate more user preferences.

**Comment by mouse0270** [comment]
Added option to expand playerlist when showing offline players in version 1.0.5 https://github.com/mouse0270/lib-themer/releases/tag/1.0.5
