### ISSUE TITLE
Health Estimate overrides Lib Themer colours.

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#25]
**_(I've returned from the pits to torment you with bug reports again now that I'm on V10.)_**

```
Foundry Virtual Tabletop Version 10
Build 288
DnD5e - Fifth Edition System 2.0.3
Hosted via Forge-VTT.com

Modules:
Health Estimate 29.5.1
Lib Themer 1.0.4
```

While [Health Estimate](https://github.com/mclemente/healthEstimate/) is installed many elements of the UI are coloured cyan/teal and the text is turned orange while "Foundry Colorized" is enabled in Lib Themer.
Most notably this affects several HUD elements including the toolbar on the left (pictured below) as well as the macro bar at the bottom of the screen.
![image](https://user-images.githubusercontent.com/35461692/197250151-dde007af-6c40-4448-a33b-b64215aefb7f.png)

**Comment by mouse0270** [comment]
Why would that module even be changing those colors? I will take a look at it and see what I can do to resolve the issue.

**Comment by mouse0270** [comment]
Can't fix it on my end, Health Estimate uses an older version of the same color library I am using. This causes a conflict. I've made a pull request for that module. https://github.com/mclemente/healthEstimate/pull/106
