### ISSUE TITLE
[Feature Request] Default Themes to be bundled.

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#27]
Currently Lib Themer does not ship with any default themes. During the early beta it had its default theme as well as the Cobalt Theme.

These served as both a useful demo for the sort of styles that were possible as well as an easy way to reset all settings back to their default value, which is not currently possible without painstakingly resetting all settings individually or making a backup immediately upon loading LibThemer for the first time.

Shipping LibThemer with a few attached themes would make it easier to understand and easier to reset when a user inevitably breaks something.

**Comment by mouse0270** [comment]
I did actually have this idea, if you look at the github, there is a presets folder, but those appear to not be included in the actual release. Seems like a small oversight and should be easy to fix on my end.

**Comment by mouse0270** [comment]
Added two default themes that can be enabled via a settings in the settings window in version 1.0.5 https://github.com/mouse0270/lib-themer/releases/tag/1.0.5
