### ISSUE TITLE
Colours cannot be reset to default without lib - Color Settings

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#29]
When attempting to reset a colour back to its default settings without lib - Color Settings installed the colour is instead reset to pure black.

My presumption would be that this is caused by the lack of transparency options with the default colour picker causing the colours to reset to an invalid value (Default Foundry colours accept #RRGGBB whereas lib - Color Settings uses #RRGGBBOO)

lib - Color Settings is currently not set as a required module and likely should be to prevent issues like this and to allow Lib Themer to properly function as intended.

**Comment by mouse0270** [comment]
Fixed in version 1.0.5 https://github.com/mouse0270/lib-themer/releases/tag/1.0.5
