### ISSUE TITLE
Pop out Right menu windows lose theming

### ISSUE THREAD

**Issue by jfrazierjr** [mouse0270/lib-themer#34]
When right clicking Actor, Encounter, Chat, etc icons on the right side bar to pop out a window, the created window loses some/all of it's theming.   

Example below:
![image](https://user-images.githubusercontent.com/2130984/199533094-1aa7ed90-5544-4102-98cd-72cde377e7bd.png)

**Comment by mouse0270** [comment]
This is probably me doing something stupid like `#sidebar` instead of specifying a class over a id. I'll take a look after work tonight.

**Comment by mouse0270** [comment]
This is also a Fantasy RGP UI Bug.

**Comment by jfrazierjr** [comment]
Not a huge issue as I don't really use those pop outs.. just something I noticed.    Also, if you ahve questions or want me to test anything, feel free to hit me up either here or on discord( I am also in the League's discord as well as the base Foundry)

**Comment by mouse0270** [comment]
This should be resolved in v0.4.0 https://github.com/mouse0270/fantasy-rpg-ui/releases/tag/0.4.0
