### ISSUE TITLE
Custom settings are not properly saved/displayed when re-opening the Theming Menu

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#4]
When using a Custom preset (not using local storage) opening the Theming Menu will not show any of the custom settings, though they do still persist until changed.

![image](https://user-images.githubusercontent.com/35461692/134426861-2b907e8f-96de-48fb-9ca6-ffd3a7c4337b.png)

![image](https://user-images.githubusercontent.com/35461692/134427237-ea6bfdf8-d644-4e13-b40f-5881aaa6ec97.png)

![image](https://user-images.githubusercontent.com/35461692/134427259-bf4209f0-017f-47e5-8441-098e26e1b3e2.png)

**Comment by mouse0270** [comment]
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json
