### ISSUE TITLE
UI Toast Font-Awesome Glyphs Break in pf2e on chrome

### ISSUE THREAD

**Issue by esheyw** [mouse0270/lib-themer#46]
![](https://i.imgur.com/YhQPOew.png) This is what I get with the current versions of everything in the stack: chrome, foundry, pf2e, libthemer. Doesn't break in Firefox current, or Brave current.
![](https://i.imgur.com/1DLv7yb.png) dnd5e doesn't even give the broken glyph icon, just nothing, in chrome-based browsers
![](https://i.imgur.com/Hy5jo3V.png) dnd5e in firefox does this

**Comment by mouse0270** [comment]
I think this is fixed in v1.0.7
