### ISSUE TITLE
[Feature Request] Loading Screen progress bar

### ISSUE THREAD

**Issue by Opius134** [mouse0270/lib-themer#49]
Not sure if this is even within the realm of possibility, but I'll toss it out there just in case.
For context: I'm self hosting. Whenever my players load in, once they get past the login screen there's a bit of a wait to get into game proper. With no visual tell beyond the big loading text, there's often times a moment where the players will question _if_ game will load, or if they'll need to reload their page, etc. 

The new loading screen is a nice feature! But some of the feedback I've gotten from my players is "now what, do I wait?" and similar responses. 

Granted, a lot of the hesitation and uncertainty is on me for my excessive mod use and admittedly ramshackle setup. Still, I think a progress bar (or even some means to customize it with a little animation) would let players know that the system hasn't outright frozen. Do you think something like that would be possible to implement some day? Thanks for your time!

**Comment by mouse0270** [comment]
Yeah, I can probably make the loading screen a little more pretty.

Its kinda something I threw on after getting asked for it quite a bit, so its not really prefect, yet. 

If I can do something like a progress bar, I might be able to at least have it show a loading indicator so users know its not frozen in place.

**Comment by mouse0270** [comment]
How does something like this feel: https://streamable.com/qaqy28
Code from: https://codepen.io/Craaftx/pen/ExyYRMK by Guilmain Dorian
Concept from: https://dribbble.com/shots/5872922-Shape-wizard by Kay Lousberg

**Comment by Opius134** [comment]
That's fantastic, actually. Would it be possible to load in a custom webm or animated gif? My players are a bunch of filthy memers, and I'm sure this applies to many Dms! 

That said, even if it's not possible/easy to implement, the example you shared is pretty much perfect for my use case!
