### ISSUE TITLE
Feature Request: Custom UI Font

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#6]
Other UI Modules such as [Ernie's Modern UI](https://github.com/ernieayala/ernies-modern-layout) and [Whetstone](https://github.com/MajorVictory/Whetstone) (Feature appears to currently be broken/non-functional as of its latest release) offer the ability to change the font used throughout Foundry.

The supported [Twilight UI](https://github.com/Rayuaz/twilight-ui) module also uses a custom typeface in it's design to better suit it's visual style.

A similar feature to Ernie's Modern UI where a user can load a Google Font using the [Google Fonts API](https://developers.google.com/fonts/) or using Foundry's module-expandable list of fonts (such as how [Custom Nameplates](https://github.com/earlSt1/vtt-custom-nameplates) works) would be an incredibly useful feature for anyone seeking to make their campaign's UI a little more visually coherent.

**Comment by mouse0270** [comment]
Fixed in v1.0.0 for Foundry v10.

Current found: https://github.com/mouse0270/lib-themer/releases/download/1.0.0/module.json
