### ISSUE TITLE
Private Rolls are not recoloured/themed.

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#7]
Private Rolls retain their default colour scheme. This has the compounding issue of making rolls when using a dark theme illegible as the white text cannot be read against the default light grey.

Pictured below (left) default view and (right) Cobalt theme.

![image](https://user-images.githubusercontent.com/35461692/134525690-fe85f2ee-9746-4ec6-8bba-312ebc3a32e2.png) ![image](https://user-images.githubusercontent.com/35461692/134525326-1af96731-f5c3-43d7-b31e-b76edb56ad3b.png)

EDIT: Possibly useful to note that when using Twilight UI and Lib Themer the issue occurs in reverse as Twilight UI defaults to a darker background which makes dark text illegible. This may also need to be resolved with another update to improve compatibility.

Pictured below Twilight UI and Lib Themer will the Core Foundry Theme and all settings enabled to enable recolouring.

![image](https://user-images.githubusercontent.com/35461692/134529103-f9b538bb-c97e-4354-b6a1-c02a782c2545.png)

**Comment by mouse0270** [comment]
Where were you a month ago when I needed people testing all of these UI things? LOL

But yeah, I am actually pretty new to foundry, like started using it in July new. So I probably missed a lot of UI colors so if you catch them, just let me know so I can keep track of them and update them as I go.

**Comment by mouse0270** [comment]
Fixed in v0.1.0b for Foundry v10.

Current beta found: https://github.com/mouse0270/lib-themer/releases/download/0.1.0b/module.json
