### ISSUE TITLE
Some style changes are incorrectly linked to TidyUI

### ISSUE THREAD

**Issue by XtraButtery** [mouse0270/lib-themer#9]
When "Enable Tidy UI - Game Settings" is checked the settings tab in Foundry is altered in ways that do not reflect changes made by the Tidy UI module.

While the changes are actually quite visually appealing they are not correctly labelled and make further changes than what is implied by the setting and as such should be separated out into different options or partially merged/integrated into the default Foundry VTT Settings options.

Pictured below (in order left-right) Foundry's default appearance; Foundry with only Tidy UI installed, 

![image](https://user-images.githubusercontent.com/35461692/134547200-8347a034-f5bc-4363-be16-eb5e615b59ab.png) ![image](https://user-images.githubusercontent.com/35461692/134549510-f7f3daf5-ca8e-4b02-abb2-408f4d74d11d.png) ![image](https://user-images.githubusercontent.com/35461692/134550109-7b1e1e59-e626-4552-b911-20f452cfb8f0.png) ![image](https://user-images.githubusercontent.com/35461692/134550013-e139da8e-a14f-4124-8d38-2d73e94b0ceb.png)

Lib Themer and Tidy UI without "Enable Tidy UI - Game Settings" is identical to only using Tidy UI Game Settings.

**Comment by mouse0270** [comment]
Yeah, I actually took tidyUI a step further. I should update the description to state this it my take on tidyUI and not a direct match. This is working as intended.
